version: "3.4"

x-app: &app
  build: .
  image: stimulus-reflex-playground:1.0.0
  tmpfs:
    - /tmp
  stdin_open: true
  tty: true
  environment: &app_env
    ACTION_CABLE_ADAPTER: any_cable
    REDIS_URL: redis://redis:6379/0
    REDIS_SIDEKIQ_URL: redis://redis:6379/1
    CABLE_URL: ws://localhost:8080/cable
    WEBPACKER_DEV_SERVER_HOST: webpacker
    ANYCABLE_REDIS_URL: redis://redis:6379/3
    ANYCABLE_RPC_HOST: anycable:50051
    ANYCABLE_HOST: 0.0.0.0
    ANYCABLE_DEBUG: 0

services:
  rails:
    <<: *app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:cached
    depends_on:
      - db
      - webpacker

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: stimulusreflex_development
      MYSQL_ROOT_PASSWORD: root
    command:
      --max_allowed_packet=1073741824
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'
      timeout: 5s
      retries: 5

  sidekiq:
    <<: *app
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/usr/src/app
      - ./config/sidekiq.yml:/usr/src/app/config/sidekiq.yml
    depends_on:
      - rails
      - redis
    environment:
      <<: *app_env
      REDIS_URL: redis://redis:6379/1

  redis:
    image: redis:6.0.6
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/:/data
    command: ["--appendonly yes"]
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  webpacker:
    build: .
    command: bash -c "yarn && bin/webpack-dev-server"
    volumes:
      - .:/usr/src/app
    ports:
      - 3035:3035
    environment:
      <<: *app_env
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  websocket:
    image: anycable/anycable-go:latest
    ports:
      - 8080:8080
    environment:
      <<: *app_env
    depends_on:
      - redis

  anycable:
    <<: *app
    command: bundle exec anycable
    environment:
      <<: *app_env
    ports:
      - 50051
    depends_on:
      - websocket
      - redis
