version: "3.3"

services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
      - webpacker
    environment:
      ACTION_CABLE_ADAPTER: any_cable
      REDIS_URL: redis://redis:6379/0
      REDIS_SIDEKIQ_URL: redis://redis:6379/1
      CABLE_URL: ws://localhost:8080/cable
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: stimulusreflex_development
      MYSQL_ROOT_PASSWORD: root
    command:
      --max_allowed_packet=1073741824
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: mysql --user=root --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'
      timeout: 5s
      retries: 5

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
      - ./config/sidekiq.yml:/app/config/sidekiq.yml
    depends_on:
      - app
      - redis
    environment:
      REDIS_URL: redis://redis:6379/1

  redis:
    image: redis:6.0.6
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/:/data
    command: ["--appendonly yes"]
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  webpacker:
    build: .
    command: bash -c "yarn && rm -rf /app/public/packs && bin/webpack-dev-server"
    volumes:
      - .:/app
    ports:
      - 3035:3035
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

  ws:
    image: anycable/anycable-go:1.0
    ports:
      - 8080:8080
    environment:
      ANYCABLE_HOST: 0.0.0.0
      ANYCABLE_REDIS_URL: redis://redis:6379/0
      ANYCABLE_RPC_HOST: anycable:50051
      ANYCABLE_DEBUG: 1
    depends_on:
      - redis

  anycable:
    build: .
    command: bundle exec anycable
    environment:
      REDIS_URL: redis://redis:6379/0
      WEBPACKER_DEV_SERVER_HOST: webpacker
      ANYCABLE_REDIS_URL: redis://redis:6379/0
      ANYCABLE_RPC_HOST: 0.0.0.0:50051
      ANYCABLE_DEBUG: 1
    ports:
      - 50051
    depends_on:
      - ws
      - redis
